version: '3'
services:
  redis:
    image: 'redis:alpine'
    volumes:
      - '/data/redis:/data'
    ports:
      - '127.0.0.1:6379:6379'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 3
        window: 30s

